server:
  port: 8080  #Swagger localhost:8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MyDatabase  # PgAdmin localhost:80
    username: postgres
    password: myforpgdbpar
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false  # Убирает warn при запуске
  kafka:
    bootstrap-servers: localhost:9092 # Kafka UI port:8081
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
app:
  kafka:
    topic: user.events.v2