server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MyDatabase
    username: postgres
    password: myforpgdbpar

  jpa:
    hibernate:
      ddl-auto: update  # Для обучения удобно: Hibernate сам создаст/обновит таблицы
    show-sql: true      # Печатает SQL в консоль
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
