server:
  port: 8080  #TODO сделать swagger

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MyDatabase
    username: postgres
    password: myforpgdbpar

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false  # Убирает warn при запуске

